### ISSUE TITLE
[Tracking Issue] New Components topic sections

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor.Docs#57]
* [ ] Component libraries
* [ ] Routing
* [ ] Built-in Blazor components (as of 0.2.0: NavLink)
* [ ] Creating components in C# (F#/VB ?)
* [ ] Logging
* [ ] Error handling
* [ ] Partial classes (not available as of 0.2.0) and/or `BlazorComponent` base classes

**Comment by danroth27** [comment]
Closing as all the proposed changes are tracked by separate issues

**Comment by guardrex** [comment]
I was thinking along the lines that this is a tracking issue for *only the Components topic* ... that these would end up being sections and that we'd track the work here.

**Comment by guardrex** [comment]
I'll move this information WRT new sections for the Components topic that isn't an issue yet over to the high-level planning outline ... just so that we have an easy spot to keep it for reference.

**Comment by guardrex** [comment]
@danroth27 I updated the high-level planning outline with the work done and your notes above.

btw - We originally had "NavLink" in a section of the Components topic called "Built-in Blazor components."

https://github.com/aspnet/Blazor.Docs/wiki/Blazor-high-level-planning

**Comment by danroth27** [comment]
I'd like to move NavLink and the routing content from the current Components article into the new Routing topic.
